/// Flutter icons PlanetIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PlanetIcons
///      fonts:
///       - asset: fonts/PlanetIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PlanetIcons {
  PlanetIcons._();

  static const _kFontFam = 'PlanetIcons';
  static const String? _kFontPkg = null;

  static const IconData saturno = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jupiter = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marte = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData planeta_terra = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData venus = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mercurio = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sol = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lua_nova = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData netuno = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData urano = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
